spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/japshop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none #기본으로 create-drop 으로 돌아감. 애플리케이션 종료 후 드랍해줌
    properties:
      hibernate:
# 운영에서는 sout 대신 로그로 찍는다.
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: true #default : true 상태.

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
